directories:
  "script":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "test":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false

exclude_paths:
  - test/dummy
