# Load Rubocop plugins.
require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance

inherit_gem:
  gemwork: lib/rubocop/.rubocop.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - bin/test
    - test/dummy/**/*
